name: Run Tests

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Git credentials to access private noir-json-parser-lib repo
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo "machine github.com login grasshopper47 password ${{ secrets.PRIVATE_REPO_SECRET }}" > ~/.netrc

      - name: Checkout tests repo
        uses: actions/checkout@v2

      - name: Install nargo 0.11.1
        run: |
          cd ../
          url="https://github.com/noir-lang/noir/releases/download/v0.11.1/nargo-x86_64-unknown-linux-gnu.tar.gz"
          curl -L "$url" | tar -xz -C .
          chmod +x nargo

      - name: Fetch noir-json-parser-lib repo
        run: |
          cd ../
          git clone https://github.com/grasshopper47/noir-json-parser-lib.git

      - name: Run nargo tests
        run: |
          ../nargo test --show-output
